# Generated by Django 2.0.6 on 2019-05-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAdds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(blank=True, max_length=20, null=True)),
                ('a_address', models.CharField(blank=True, max_length=40, null=True)),
                ('post_id', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_adds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=40, null=True)),
                ('author', models.CharField(blank=True, max_length=40, null=True)),
                ('press', models.CharField(blank=True, max_length=40, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=40, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=40, null=True)),
                ('word_number', models.CharField(blank=True, max_length=10, null=True)),
                ('page_number', models.CharField(blank=True, max_length=10, null=True)),
                ('book_size', models.CharField(blank=True, max_length=10, null=True)),
                ('paper', models.CharField(blank=True, max_length=10, null=True)),
                ('packing', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('dd_price', models.FloatField(blank=True, null=True)),
                ('editor_rec', models.CharField(blank=True, max_length=2000, null=True)),
                ('about_content', models.CharField(blank=True, max_length=2000, null=True)),
                ('about_author', models.CharField(blank=True, max_length=1000, null=True)),
                ('catalog', models.CharField(blank=True, max_length=2000, null=True)),
                ('media_comm', models.CharField(blank=True, db_column='Media_comm', max_length=2000, null=True)),
                ('digest_image', models.CharField(blank=True, max_length=2000, null=True)),
                ('illustration', models.CharField(blank=True, max_length=2000, null=True)),
                ('series_name', models.CharField(blank=True, max_length=40, null=True)),
                ('printing_date', models.DateField(blank=True, null=True)),
                ('impression', models.CharField(blank=True, max_length=10, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('shelves_date', models.DateField(blank=True, null=True)),
                ('customer_score', models.FloatField(blank=True, null=True)),
                ('book_status', models.IntegerField(blank=True, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TClass',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(blank=True, max_length=20, null=True)),
                ('book_num', models.IntegerField(blank=True, null=True)),
                ('class_pid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, max_length=40, null=True)),
                ('cre_time', models.DateTimeField(blank=True, null=True)),
                ('all_price', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TOrderlterm',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_num', models.IntegerField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_orderlterm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('username', models.CharField(blank=True, max_length=60, null=True)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
    ]
